//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""e24bf8d4-599d-40eb-97bc-a5bf567aa47c"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""0b3a2ac2-caf3-40aa-90fa-245ac617cc43"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7fce429a-17d0-438d-b04f-4c12f0e3afbf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LAtk"",
                    ""type"": ""Button"",
                    ""id"": ""f6e8516f-bb3e-40e5-b504-9828c91e7a7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LAtk_Long"",
                    ""type"": ""Button"",
                    ""id"": ""207449d5-85d1-4038-a463-6625e3ea25f7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""c0a9bc62-2082-48d2-9289-60267c29686d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Button"",
                    ""id"": ""82553c91-5449-4b03-94e3-d3d9a8b6b7b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_E"",
                    ""type"": ""Button"",
                    ""id"": ""2badeba7-5f6a-41dd-8e6c-079b057f660c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_E_Long"",
                    ""type"": ""Button"",
                    ""id"": ""d0cb0055-7171-4b5a-8465-364e6f3666bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_Q"",
                    ""type"": ""Button"",
                    ""id"": ""07ff596c-add9-4d47-b7f2-4c35b745ffc9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_Q_Long"",
                    ""type"": ""Button"",
                    ""id"": ""af12dea5-7235-4634-b97f-a4659a1da861"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""5e34e542-0039-40bf-be6a-c56f8e557264"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""18de136b-ad5e-416e-8e69-5a9889b5c7bc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Defen"",
                    ""type"": ""Button"",
                    ""id"": ""a99ae187-5150-426d-9ed4-1b59ccdf1f6d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_F"",
                    ""type"": ""Button"",
                    ""id"": ""a053ae37-6ada-426d-99bf-a1f3d8a0f18d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combat_F_Long"",
                    ""type"": ""Button"",
                    ""id"": ""b43208c2-ae11-4c6f-92cb-e98582fa80ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""d30539eb-19a1-43cb-b116-8164c85308dd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""57c1a2a2-dccc-4005-9865-2a9830462550"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-0.1,max=0.1),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""6308b9cf-70f4-43aa-8971-2889ad05ae71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a23ef2f2-22da-4557-872b-3aec6b23ac0d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebcd58bc-60fa-401e-a2cc-df6c3eaab394"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""915ca90e-6e98-455b-8ba6-72ccea95a60f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""363df97d-7937-4ffb-ab40-b9d483a40af6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6ae133c1-8cb3-4540-a4ca-e29b0c564464"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""164095bb-ec99-42ba-b0b4-c00a99682845"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05b57ff1-b677-4ef7-80d9-85b2001916b9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""368ba2b7-f0fe-40e6-a212-443223881729"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""468a547f-6418-42af-a093-9461f70123f7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fad2917-c41b-4c9d-8414-c37d208c1ff0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af871dac-4fba-4559-87be-23e88c1b6fb7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f955aee-68c9-4574-b2a5-fdc8e516634c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_Q_Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aa14478-f50e-4314-af92-371196d0431e"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c19e3b0-777a-46e1-8fbc-ff68d1bcaef6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAtk_Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01d010b3-385e-47b1-a273-e1aec563d2a5"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d01522a-17f6-4160-a41e-caf14c421701"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Defen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b222a6b1-5242-49bb-8f6a-3dbeb8abb126"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_E_Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""872c27e0-e71b-47e4-9647-1a652ce768b7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84a81ce4-0149-4816-88a1-93e0ebf01252"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combat_F_Long"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d88c8a6-eb1e-4cee-acab-da54f517ca15"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""388b8a0b-c1e4-46d9-ba1a-c2e968f8fa64"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3641194c-0ea1-4204-9ff9-986b1352566a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Movement = m_PlayerInput.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInput_Jump = m_PlayerInput.FindAction("Jump", throwIfNotFound: true);
        m_PlayerInput_LAtk = m_PlayerInput.FindAction("LAtk", throwIfNotFound: true);
        m_PlayerInput_LAtk_Long = m_PlayerInput.FindAction("LAtk_Long", throwIfNotFound: true);
        m_PlayerInput_Interaction = m_PlayerInput.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerInput_Slide = m_PlayerInput.FindAction("Slide", throwIfNotFound: true);
        m_PlayerInput_Combat_E = m_PlayerInput.FindAction("Combat_E", throwIfNotFound: true);
        m_PlayerInput_Combat_E_Long = m_PlayerInput.FindAction("Combat_E_Long", throwIfNotFound: true);
        m_PlayerInput_Combat_Q = m_PlayerInput.FindAction("Combat_Q", throwIfNotFound: true);
        m_PlayerInput_Combat_Q_Long = m_PlayerInput.FindAction("Combat_Q_Long", throwIfNotFound: true);
        m_PlayerInput_CameraLook = m_PlayerInput.FindAction("CameraLook", throwIfNotFound: true);
        m_PlayerInput_Run = m_PlayerInput.FindAction("Run", throwIfNotFound: true);
        m_PlayerInput_Defen = m_PlayerInput.FindAction("Defen", throwIfNotFound: true);
        m_PlayerInput_Combat_F = m_PlayerInput.FindAction("Combat_F", throwIfNotFound: true);
        m_PlayerInput_Combat_F_Long = m_PlayerInput.FindAction("Combat_F_Long", throwIfNotFound: true);
        m_PlayerInput_SwitchCharacter = m_PlayerInput.FindAction("SwitchCharacter", throwIfNotFound: true);
        m_PlayerInput_Zoom = m_PlayerInput.FindAction("Zoom", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_PlayerInput.enabled, "This will cause a leak and performance issues, PlayerControls.PlayerInput.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Movement;
    private readonly InputAction m_PlayerInput_Jump;
    private readonly InputAction m_PlayerInput_LAtk;
    private readonly InputAction m_PlayerInput_LAtk_Long;
    private readonly InputAction m_PlayerInput_Interaction;
    private readonly InputAction m_PlayerInput_Slide;
    private readonly InputAction m_PlayerInput_Combat_E;
    private readonly InputAction m_PlayerInput_Combat_E_Long;
    private readonly InputAction m_PlayerInput_Combat_Q;
    private readonly InputAction m_PlayerInput_Combat_Q_Long;
    private readonly InputAction m_PlayerInput_CameraLook;
    private readonly InputAction m_PlayerInput_Run;
    private readonly InputAction m_PlayerInput_Defen;
    private readonly InputAction m_PlayerInput_Combat_F;
    private readonly InputAction m_PlayerInput_Combat_F_Long;
    private readonly InputAction m_PlayerInput_SwitchCharacter;
    private readonly InputAction m_PlayerInput_Zoom;
    public struct PlayerInputActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerInputActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInput_Movement;
        public InputAction @Jump => m_Wrapper.m_PlayerInput_Jump;
        public InputAction @LAtk => m_Wrapper.m_PlayerInput_LAtk;
        public InputAction @LAtk_Long => m_Wrapper.m_PlayerInput_LAtk_Long;
        public InputAction @Interaction => m_Wrapper.m_PlayerInput_Interaction;
        public InputAction @Slide => m_Wrapper.m_PlayerInput_Slide;
        public InputAction @Combat_E => m_Wrapper.m_PlayerInput_Combat_E;
        public InputAction @Combat_E_Long => m_Wrapper.m_PlayerInput_Combat_E_Long;
        public InputAction @Combat_Q => m_Wrapper.m_PlayerInput_Combat_Q;
        public InputAction @Combat_Q_Long => m_Wrapper.m_PlayerInput_Combat_Q_Long;
        public InputAction @CameraLook => m_Wrapper.m_PlayerInput_CameraLook;
        public InputAction @Run => m_Wrapper.m_PlayerInput_Run;
        public InputAction @Defen => m_Wrapper.m_PlayerInput_Defen;
        public InputAction @Combat_F => m_Wrapper.m_PlayerInput_Combat_F;
        public InputAction @Combat_F_Long => m_Wrapper.m_PlayerInput_Combat_F_Long;
        public InputAction @SwitchCharacter => m_Wrapper.m_PlayerInput_SwitchCharacter;
        public InputAction @Zoom => m_Wrapper.m_PlayerInput_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @LAtk.started += instance.OnLAtk;
            @LAtk.performed += instance.OnLAtk;
            @LAtk.canceled += instance.OnLAtk;
            @LAtk_Long.started += instance.OnLAtk_Long;
            @LAtk_Long.performed += instance.OnLAtk_Long;
            @LAtk_Long.canceled += instance.OnLAtk_Long;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @Slide.started += instance.OnSlide;
            @Slide.performed += instance.OnSlide;
            @Slide.canceled += instance.OnSlide;
            @Combat_E.started += instance.OnCombat_E;
            @Combat_E.performed += instance.OnCombat_E;
            @Combat_E.canceled += instance.OnCombat_E;
            @Combat_E_Long.started += instance.OnCombat_E_Long;
            @Combat_E_Long.performed += instance.OnCombat_E_Long;
            @Combat_E_Long.canceled += instance.OnCombat_E_Long;
            @Combat_Q.started += instance.OnCombat_Q;
            @Combat_Q.performed += instance.OnCombat_Q;
            @Combat_Q.canceled += instance.OnCombat_Q;
            @Combat_Q_Long.started += instance.OnCombat_Q_Long;
            @Combat_Q_Long.performed += instance.OnCombat_Q_Long;
            @Combat_Q_Long.canceled += instance.OnCombat_Q_Long;
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Defen.started += instance.OnDefen;
            @Defen.performed += instance.OnDefen;
            @Defen.canceled += instance.OnDefen;
            @Combat_F.started += instance.OnCombat_F;
            @Combat_F.performed += instance.OnCombat_F;
            @Combat_F.canceled += instance.OnCombat_F;
            @Combat_F_Long.started += instance.OnCombat_F_Long;
            @Combat_F_Long.performed += instance.OnCombat_F_Long;
            @Combat_F_Long.canceled += instance.OnCombat_F_Long;
            @SwitchCharacter.started += instance.OnSwitchCharacter;
            @SwitchCharacter.performed += instance.OnSwitchCharacter;
            @SwitchCharacter.canceled += instance.OnSwitchCharacter;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @LAtk.started -= instance.OnLAtk;
            @LAtk.performed -= instance.OnLAtk;
            @LAtk.canceled -= instance.OnLAtk;
            @LAtk_Long.started -= instance.OnLAtk_Long;
            @LAtk_Long.performed -= instance.OnLAtk_Long;
            @LAtk_Long.canceled -= instance.OnLAtk_Long;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @Slide.started -= instance.OnSlide;
            @Slide.performed -= instance.OnSlide;
            @Slide.canceled -= instance.OnSlide;
            @Combat_E.started -= instance.OnCombat_E;
            @Combat_E.performed -= instance.OnCombat_E;
            @Combat_E.canceled -= instance.OnCombat_E;
            @Combat_E_Long.started -= instance.OnCombat_E_Long;
            @Combat_E_Long.performed -= instance.OnCombat_E_Long;
            @Combat_E_Long.canceled -= instance.OnCombat_E_Long;
            @Combat_Q.started -= instance.OnCombat_Q;
            @Combat_Q.performed -= instance.OnCombat_Q;
            @Combat_Q.canceled -= instance.OnCombat_Q;
            @Combat_Q_Long.started -= instance.OnCombat_Q_Long;
            @Combat_Q_Long.performed -= instance.OnCombat_Q_Long;
            @Combat_Q_Long.canceled -= instance.OnCombat_Q_Long;
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Defen.started -= instance.OnDefen;
            @Defen.performed -= instance.OnDefen;
            @Defen.canceled -= instance.OnDefen;
            @Combat_F.started -= instance.OnCombat_F;
            @Combat_F.performed -= instance.OnCombat_F;
            @Combat_F.canceled -= instance.OnCombat_F;
            @Combat_F_Long.started -= instance.OnCombat_F_Long;
            @Combat_F_Long.performed -= instance.OnCombat_F_Long;
            @Combat_F_Long.canceled -= instance.OnCombat_F_Long;
            @SwitchCharacter.started -= instance.OnSwitchCharacter;
            @SwitchCharacter.performed -= instance.OnSwitchCharacter;
            @SwitchCharacter.canceled -= instance.OnSwitchCharacter;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLAtk(InputAction.CallbackContext context);
        void OnLAtk_Long(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
        void OnCombat_E(InputAction.CallbackContext context);
        void OnCombat_E_Long(InputAction.CallbackContext context);
        void OnCombat_Q(InputAction.CallbackContext context);
        void OnCombat_Q_Long(InputAction.CallbackContext context);
        void OnCameraLook(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnDefen(InputAction.CallbackContext context);
        void OnCombat_F(InputAction.CallbackContext context);
        void OnCombat_F_Long(InputAction.CallbackContext context);
        void OnSwitchCharacter(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
